ENCODER_ENABLE = yes
OLED_ENABLE = yes
RAW_ENABLE = yes

LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no